"""
Django settings for psb_pondok project - DEVELOPMENT MODE

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
import os
from csp.constants import NONCE

# SECRET_KEY - gunakan dari environment variable atau default
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-l%*@boeybs$z)stf)ld#0*)kjy%ka%e#)(7!lf%089wzc=#%&u')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True  # Development mode - aktifkan debug

# ALLOWED_HOSTS - untuk development, lebih permisif
ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    'rdsmahato.ponpes.id',  # Untuk testing
    'www.rdsmahato.ponpes.id',
    '.rdsmahato.ponpes.id',
]

# Jika ada environment variable ALLOWED_HOSTS, tambahkan juga
env_allowed_hosts = os.environ.get('ALLOWED_HOSTS', '')
if env_allowed_hosts:
    ALLOWED_HOSTS.extend([host.strip() for host in env_allowed_hosts.split(',')])


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',  # Untuk format angka Indonesia
    # Third Party Apps
    'django_htmx',
    'widget_tweaks',
    'django_filters',
    'django_extensions',
    'django_summernote',  # Rich Text Editor
    'axes',  # Django Axes untuk brute force protection
    'csp',  # Content Security Policy untuk mencegah XSS attacks
    'fontawesomefree',  # Font Awesome Free (static/css dari paket pip)
    # Custom Apps
    'core',
    'users',
    'admissions',
    'documents',
    'payments',
    'admin_panel',  # Menggunakan admin_panel (workaround untuk folder admin-panel)
    'blog',  # Blog/Artikel Management
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # WhiteNoise untuk serve static files di production
    'psb_pondok.middleware_debug.DebugRequestLogMiddleware',  # debug instrumentation
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'axes.middleware.AxesMiddleware',  # Axes middleware - harus setelah AuthenticationMiddleware
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'csp.middleware.CSPMiddleware',  # Content Security Policy middleware
    # HTMX Middleware - harus setelah AuthenticationMiddleware
    'django_htmx.middleware.HtmxMiddleware',
    # HTML Minification - setelah semua middleware lainnya
]

ROOT_URLCONF = 'psb_pondok.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',  # Debug context processor untuk development
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.website_settings',  # WebsiteSettings untuk semua template
            ],
        },
    },
]

WSGI_APPLICATION = 'psb_pondok.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        # Untuk development localhost, gunakan environment variable atau default
        'NAME': os.environ.get('DB_NAME', 'ponpes'),  # Database localhost: ponpes
        'USER': os.environ.get('DB_USER', 'root'),  # Default root untuk localhost
        'PASSWORD': os.environ.get('DB_PASSWORD', ''),  # Default empty untuk localhost
        'HOST': os.environ.get('DB_HOST', 'localhost'),
        'PORT': os.environ.get('DB_PORT', '3306'),
        'OPTIONS': {
            'charset': 'utf8mb4',
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
            'connect_timeout': 10,
        },
        # Workaround untuk MariaDB versi lama
        'CONN_MAX_AGE': 0,
    }
}

# Disable RETURNING clause untuk MariaDB 10.4 (tidak support RETURNING)
# Django 5.2+ menggunakan RETURNING untuk INSERT, tapi MariaDB 10.4 tidak support
from django.db.backends.mysql.features import DatabaseFeatures
DatabaseFeatures.can_return_columns_from_insert = False


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'id-id'

TIME_ZONE = 'Asia/Jakarta'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static']

# WhiteNoise Configuration - untuk serve static files di production
# WhiteNoise akan serve static files secara otomatis tanpa perlu Apache/nginx
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# WhiteNoise settings
WHITENOISE_USE_FINDERS = True  # Gunakan staticfiles finders saat DEBUG=True
WHITENOISE_AUTOREFRESH = True  # Auto-refresh saat DEBUG=True (development)
WHITENOISE_MANIFEST_STRICT = False  # Tidak strict untuk development

# Media files (Uploaded files)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Custom User Model
AUTH_USER_MODEL = 'users.User'

# Authentication Backends - Axes harus di akhir
AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesBackend',  # Axes backend untuk brute force protection
    'django.contrib.auth.backends.ModelBackend',  # Default Django backend
]

# Login URLs
LOGIN_URL = 'users:login'
LOGIN_REDIRECT_URL = 'admin-panel:index'
LOGOUT_REDIRECT_URL = 'users:login'  # Redirect ke login setelah logout

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Summernote Configuration
SUMMERNOTE_THEME = 'bs4'  # Bootstrap 4
SUMMERNOTE_CONFIG = {
    'summernote': {
        'width': '100%',
        'height': '500',
        'toolbar': [
            ['style', ['style']],
            ['font', ['bold', 'italic', 'underline', 'clear']],
            ['fontname', ['fontname']],
            ['fontsize', ['fontsize']],
            ['color', ['color']],
            ['para', ['ul', 'ol', 'paragraph']],
            ['table', ['table']],
            ['insert', ['link', 'picture', 'video']],
            ['view', ['fullscreen', 'codeview', 'help']],
        ],
    },
    'attachment_filesize_limit': 1024 * 1024 * 5,  # 5MB
}

# Development Settings - Security settings lebih ringan
# Tidak menggunakan security settings ketat untuk development
SECURE_BROWSER_XSS_FILTER = False
SECURE_CONTENT_TYPE_NOSNIFF = False
X_FRAME_OPTIONS = 'SAMEORIGIN'  # Lebih permisif untuk development
SECURE_HSTS_SECONDS = 0  # Disable HSTS di development
SECURE_HSTS_INCLUDE_SUBDOMAINS = False
SECURE_HSTS_PRELOAD = False

# Session security - lebih ringan untuk development
SESSION_COOKIE_SECURE = False  # Allow HTTP di development
CSRF_COOKIE_SECURE = False  # Allow HTTP di development
SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_HTTPONLY = True

# Session Timeout - 1 jam (3600 detik)
SESSION_COOKIE_AGE = 3600  # 1 jam dalam detik
SESSION_SAVE_EVERY_REQUEST = True  # Refresh session setiap request untuk extend timeout
SESSION_EXPIRE_AT_BROWSER_CLOSE = False  # Session tetap aktif meskipun browser ditutup (sampai timeout)

# SSL/HTTPS settings - tidak diperlukan di development
SECURE_SSL_REDIRECT = False

# Content Security Policy (CSP) - FORMAT BARU (django-csp >= 4)
# Exclude static dan media files dari CSP (tidak perlu CSP untuk static files)
CONTENT_SECURITY_POLICY = {
    'DIRECTIVES': {
        'default-src': ("'self'",),
        'script-src': (
            "'self'",
            "'unsafe-inline'",
            "'unsafe-eval'",
            "https://cdn.jsdelivr.net",
            "https://code.jquery.com",
            "http://code.jquery.com",  # Fallback untuk HTTP (development)
            "https://cdnjs.cloudflare.com",
            "https://unpkg.com",
            "http://stackpath.bootstrapcdn.com",  # Untuk Summernote (development)
            NONCE,
        ),
        'style-src': (
            "'self'",
            "'unsafe-inline'",
            "https://cdn.jsdelivr.net",
            "https://cdnjs.cloudflare.com",
            "http://cdnjs.cloudflare.com",  # Fallback untuk HTTP (development)
            "http://stackpath.bootstrapcdn.com",  # Untuk Summernote Bootstrap (development)
            "https://fonts.googleapis.com",
            NONCE,
        ),
        'img-src': (
            "'self'",
            "data:",
            "https:",
            "http:",
        ),
        'font-src': (
            "'self'",
            "https://fonts.gstatic.com",
            "https://cdnjs.cloudflare.com",
            "data:",
        ),
        'connect-src': (
            "'self'",
            "https://stackpath.bootstrapcdn.com",
            "http://stackpath.bootstrapcdn.com",  # Fallback untuk development
            "https://cdn.jsdelivr.net",
            "https://cdnjs.cloudflare.com",
        ),
        'frame-src': ("'self'", "https://www.google.com", "https://maps.google.com"),
        'object-src': ("'none'",),
        'base-uri': ("'self'",),
        'form-action': ("'self'",),
        'frame-ancestors': ("'self'",),
    },
    'EXCLUDE_URL_PREFIXES': ('/static/', '/media/'),
    'REPORT_ONLY': False,
}

# Security Headers tambahan
SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'  # Referrer Policy
SECURE_CROSS_ORIGIN_OPENER_POLICY = 'same-origin'  # COOP
SECURE_CROSS_ORIGIN_EMBEDDER_POLICY = 'require-corp'  # COEP (relaxed untuk development)

# CSRF Protection - Enhanced
CSRF_COOKIE_SAMESITE = 'Lax'  # Lax untuk development, Strict untuk production
CSRF_USE_SESSIONS = False  # Gunakan cookie-based CSRF
CSRF_COOKIE_AGE = None  # Session-based, expire saat browser close
CSRF_FAILURE_VIEW = 'django.views.csrf.csrf_failure'  # Custom view jika diperlukan

# Session Security - Enhanced
SESSION_COOKIE_SAMESITE = 'Lax'  # Lax untuk development
SESSION_COOKIE_NAME = 'sessionid'  # Default Django session cookie name
SESSION_ENGINE = 'django.contrib.sessions.backends.db'  # Database-backed sessions

# Password Validation - Enhanced (sudah ada, tapi kita pastikan lengkap)
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 8,  # Minimum 8 karakter
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Django Axes Configuration - Brute Force Protection
# Axes melindungi aplikasi dari brute force attack dengan:
# - Mencatat setiap percobaan login yang gagal
# - Mengunci IP/username setelah melebihi batas percobaan
# - Menyimpan data di database untuk tracking
AXES_ENABLED = True
AXES_FAILURE_LIMIT = 5  # Lock setelah 5 percobaan gagal
AXES_COOLOFF_TIME = 1  # Lock selama 1 jam (dalam jam)
AXES_LOCKOUT_TEMPLATE = None  # Gunakan default lockout message
AXES_LOCKOUT_URL = None  # Gunakan default lockout response
AXES_VERBOSE = True  # Log lockout events ke console
AXES_RESET_ON_SUCCESS = True  # Reset counter setelah login berhasil

# Rate Limiting Configuration (menggunakan cache)
# Rate limiting untuk form submission dan API endpoints
RATELIMIT_ENABLE = True  # Enable rate limiting
RATELIMIT_USE_CACHE = 'default'  # Gunakan default cache
RATELIMIT_RATE = '100/h'  # 100 requests per hour per IP (default)
RATELIMIT_KEY = 'ip'  # Rate limit berdasarkan IP address

# Rate limiting untuk endpoint spesifik (dapat di-override di views)
RATELIMIT_LOGIN = '5/m'  # 5 login attempts per minute
RATELIMIT_REGISTER = '3/h'  # 3 registrations per hour per IP
RATELIMIT_FORM_SUBMIT = '20/h'  # 20 form submissions per hour per IP
RATELIMIT_API = '100/h'  # 100 API requests per hour per IP

# File Upload Security
FILE_UPLOAD_MAX_MEMORY_SIZE = 2621440  # 2.5 MB - file kecil di memory
DATA_UPLOAD_MAX_MEMORY_SIZE = 2621440  # 2.5 MB
DATA_UPLOAD_MAX_NUMBER_FIELDS = 1000  # Limit jumlah fields
FILE_UPLOAD_PERMISSIONS = 0o644  # File permissions
FILE_UPLOAD_DIRECTORY_PERMISSIONS = 0o755  # Directory permissions

# Logging Configuration - menggunakan default Django
# Tidak ada konfigurasi logging khusus, menggunakan default Django logging

# Development-specific settings
# Email backend untuk development (console output)
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# Django Extensions - untuk development tools
# IPython shell
SHELL_PLUS = 'ipython'

# Internal IPs untuk debug toolbar (jika digunakan)
INTERNAL_IPS = [
    '127.0.0.1',
    'localhost',
]

# Security Logging - Development
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
        'security': {
            'format': 'SECURITY {levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'security_file': {
            'level': 'WARNING',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs' / 'security.log',
            'formatter': 'security',
        },
    },
    'loggers': {
        'django.security': {
            'handlers': ['console', 'security_file'],
            'level': 'WARNING',
            'propagate': False,
        },
        'axes': {
            'handlers': ['console', 'security_file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# Buat direktori logs jika belum ada
import os
logs_dir = BASE_DIR / 'logs'
if not os.path.exists(logs_dir):
    os.makedirs(logs_dir)

