# Generated by Django 5.2.8 on 2025-12-02 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_informasitambahan'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitesettings',
            name='maintenance_message',
            field=models.TextField(blank=True, default='Website sedang dalam perawatan. Kami akan kembali segera.', help_text='Pesan yang akan ditampilkan saat maintenance mode aktif', verbose_name='Pesan Maintenance'),
        ),
        migrations.AddField(
            model_name='websitesettings',
            name='maintenance_mode',
            field=models.BooleanField(default=False, help_text='Aktifkan untuk menampilkan halaman maintenance', verbose_name='Mode Maintenance'),
        ),
    ]
