# Generated by Django 5.2.8 on 2025-12-21 10:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_websitesettings_maintenance_message_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gambar', models.ImageField(help_text='Upload gambar (JPG, PNG, WebP)', upload_to='media-library/%Y/%m/%d/', verbose_name='Gambar')),
                ('judul', models.CharField(help_text='Judul/nama gambar untuk memudahkan pencarian', max_length=200, verbose_name='Judul')),
                ('deskripsi', models.TextField(blank=True, help_text='Deskripsi gambar (opsional)', verbose_name='Deskripsi')),
                ('kategori', models.CharField(choices=[('hero', 'Hero Section'), ('program', 'Program/Kegiatan'), ('dokumentasi', 'Dokumentasi'), ('media', 'Media Gallery'), ('fasilitas', 'Fasilitas'), ('ekstrakurikuler', 'Ekstrakurikuler'), ('sejarah', 'Sejarah'), ('program_pendidikan', 'Program Pendidikan'), ('umum', 'Umum')], default='umum', help_text='Kategori gambar untuk memudahkan filter', max_length=50, verbose_name='Kategori')),
                ('tags', models.CharField(blank=True, help_text='Tags dipisahkan dengan koma (contoh: kegiatan, acara, pembelajaran)', max_length=500, verbose_name='Tags')),
                ('alt_text', models.CharField(blank=True, help_text='Deskripsi gambar untuk SEO dan accessibility', max_length=200, verbose_name='Alt Text (SEO)')),
                ('ukuran_file', models.PositiveIntegerField(blank=True, null=True, verbose_name='Ukuran File (bytes)')),
                ('lebar', models.PositiveIntegerField(blank=True, null=True, verbose_name='Lebar (px)')),
                ('tinggi', models.PositiveIntegerField(blank=True, null=True, verbose_name='Tinggi (px)')),
                ('format_file', models.CharField(blank=True, max_length=10, verbose_name='Format File')),
                ('is_featured', models.BooleanField(default=False, help_text='Tandai sebagai gambar unggulan', verbose_name='Unggulan')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Urutan')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Diupdate')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_images_created', to=settings.AUTH_USER_MODEL, verbose_name='Dibuat Oleh')),
            ],
            options={
                'verbose_name': 'Media Image',
                'verbose_name_plural': 'Media Images',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['kategori', '-created_at'], name='core_mediai_kategor_e51962_idx'), models.Index(fields=['judul'], name='core_mediai_judul_802dbc_idx')],
            },
        ),
    ]
