# Generated by Django 5.2.8 on 2025-12-21 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_mediaimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MediaImage',
        ),
    ]
