# Generated by Django 6.0 on 2025-12-22 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_delete_mediaimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herosection',
            name='image',
            field=models.ImageField(blank=True, help_text='Gambar dapat dipilih dari gallery atau diupload manual', null=True, upload_to='hero/%Y/%m/%d/', verbose_name='Gambar'),
        ),
    ]
