# Generated by Django 5.2.8 on 2025-12-21 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='convertedimage',
            name='judul',
            field=models.CharField(blank=True, default='', help_text='Judul gambar untuk memudahkan pencarian', max_length=200, verbose_name='Judul'),
        ),
    ]
