# Generated by Django 6.0 on 2025-12-23 12:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_convertedimage_judul'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BugNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Judul')),
                ('description', models.TextField(blank=True, verbose_name='Deskripsi')),
                ('page_url', models.URLField(blank=True, verbose_name='URL Halaman')),
                ('status', models.CharField(choices=[('open', 'Open'), ('progress', 'In Progress'), ('closed', 'Closed')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bug_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Catatan Bug',
                'verbose_name_plural': 'Catatan Bug',
                'ordering': ['-created_at'],
            },
        ),
    ]
