# Generated by Django 5.2.8 on 2025-12-21 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogImage',
        ),
    ]
